
services:
  frontend:
    build: frontend
    ports:
      - 4200:4200
    depends_on:
      - backend
    volumes:
      - ./storage:/storage

  backend:
    build: backend
    ports:
      - 8080:8080
    volumes:
      - ./storage:/storage
